name: Import my posts from DEV
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erikaheidi/importDevTo@v1
        name: "Import posts from a DEV user"
        env:
          DEVTO_USERNAME: erikaheidi
      - name: Create a PR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Import DEV posts
          title: "[automated] Import posts from DEV"
          token: ${{ secrets.GITHUB_TOKEN }}
